version: '3.8'

services:
  app:
    image: pawong/backend:latest
    container_name: backend-app

    env_file:
      - .env

    ports:
      - "${APP_PORT}:8080"
    restart: always

    # only your profile var here; the rest come from .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod