version: '3.8'

services:
  app:
    image: pawong/backend:latest      # ← pull this instead of building
    container_name: backend-app       # ← match the name you’ve been inspecting
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    restart: unless-stopped