version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    restart: unless-stopped