spring:
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # OpenAPI/Swagger ??
  doc:
    api-docs:
      path: /v3/api-docs      # OpenAPI 3.0
    swagger-ui:
      path: /swagger-ui.html  # Swagger UI
      operationsSorter: alpha
      tagsSorter: alpha

server:
  port: ${APP_PORT:8080}