name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/backend
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:$TAG

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG

      - name: SSH to deploy server and update
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            # 1) 올바른 배포 디렉터리로 이동
            cd /home/${{ secrets.DEPLOY_USER }}/backend

            # 2) IMAGE_NAME, TAG 재정의
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/backend
            TAG=${{ github.sha }}

            # 3) 안전한 로그인 (password-stdin)
            echo "${{ secrets.DOCKERHUB_TOKEN }}" \
              | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # 4) 이미지 풀 & 태그 교체
            docker pull "${IMAGE_NAME}:latest"
            docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:current"

            # 5) Compose 파일이 있는 위치에서만 pull/up
            docker-compose pull
            docker-compose up -d --no-deps app